### PR TITLE
Support for scanning of multiple barcodes in one image: New option "mult...

### PR DESCRIPTION
**Pull request by elwerene**
...i"

### CODE REVIEW

**Comment by elwerene** [comment]
thx

**Comment by thomaschaaf** [comment]
sorry for taking so long :(

**Comment by amtdevops** [comment]
@matthiasg  @elwerene

Hi, It's not working for me. I am getting only one barcode as a response 

Tried this image  - https://drive.google.com/open?id=1lk-gptDtFYP_AO16OehaZIqs2asYLXMO

got the response as - 8806088148779, but didn't get the second barcode. 

I am trying with  'multi: true' option. 

  ```
qrdecoder.decode(path,
  	function (err, out) {
  	var barCode = null;
  	console.log('result', err, out);
  	if (!err && out) {
  		barCode = out ? out : null;
  		console.log('BarCodeExtract 1st try NodeZxing', barCode);

  	} else {
  		console.log('Not found');
  		req.barCodeScan = barCode;
  	}})
```

**"but another call might return full information"** Do you want me to call the same decode function one more time? I tried that too but the same result returned 

Your help is much appreciated 

Seems like qrcode variable is declared as a string and giving only one QR code, Can you have time to do a quick fix?
https://github.com/komola/node-zxing/blob/master/lib/main.js#L30

**Comment by matthiasg** [comment]
@amtdevops this was years ago and I did not do the pull request :) but looking at https://github.com/komola/node-zxing/blob/95dc7d80385dc74a3a694743b73fe010b059170e/lib/main.js#L37 I would say this code needs to be changed. It is splitting the result per new line and then only returns one of them. Basically change it to qrCodes = lines.map(l => parseInt(l,10)).join('\n') ... or better dont join and add qrCodes as an extra parameter to the callback if present. that way it would be downwards compatible

**Pull request merged**
